update

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -41,44 +41,44 @@ jobs:
           name: requirements
           path: requirements.txt
 
-  # pylint:
-  #   name: PyLint
-  #   runs-on: ubuntu-latest
-  #   needs: setup-requirements
-  #   timeout-minutes: 10
+  pylint:
+    name: PyLint
+    runs-on: ubuntu-latest
+    needs: setup-requirements
+    timeout-minutes: 10
 
-  #   steps:
-  #     - name: Check out repository code
-  #       uses: actions/checkout@v4.2.2
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v4.2.2
 
-  #     # Setup Python (faster than using Python container)
-  #     - name: Setup Python
-  #       uses: actions/setup-python@v5.3.0
-  #       with:
-  #         python-version: "3.12.0"
+      # Setup Python (faster than using Python container)
+      - name: Setup Python
+        uses: actions/setup-python@v5.3.0
+        with:
+          python-version: "3.12.0"
 
-  #     - name: Install Hatch
-  #       if: steps.cache-hatch.outputs.cache-hit != 'true'
-  #       run: python -m pip install --upgrade hatch
+      - name: Install Hatch
+        if: steps.cache-hatch.outputs.cache-hit != 'true'
+        run: python -m pip install --upgrade hatch
 
-  #     - name: Cache Hatch environment
-  #       uses: actions/cache@v4.2.3
-  #       with:
-  #         path: |
-  #           ~/.cache/hatch
-  #           ~/.local/share/hatch
-  #         key: ${{ runner.os }}-hatch-${{ env.HATCH_DEP_HASH }}
+      - name: Cache Hatch environment
+        uses: actions/cache@v4.2.3
+        with:
+          path: |
+            ~/.cache/hatch
+            ~/.local/share/hatch
+          key: ${{ runner.os }}-hatch-${{ env.HATCH_DEP_HASH }}
 
-  #     # Don't fail just output, since we want the score to be above 9 not 10.0
-  #     # Don’t let the Perfect be the Enemy of the Good
-  #     - name: Pylint on esbmc_ai
-  #       run: hatch run pylint esbmc_ai || true
+      # Don't fail just output, since we want the score to be above 9 not 10.0
+      # Don’t let the Perfect be the Enemy of the Good
+      - name: Pylint on esbmc_ai
+        run: hatch run pylint esbmc_ai || true
       
-  #     # Check if pass, the test command only takes integers so truncate decimals
-  #     - name: Check If Pass (90%)
-  #       run: |
-  #         SCORE="$(sed -n '$s/[^0-9]*\([0-9.]*\).*/\1/p' <<< "$(hatch run pylint esbmc_ai)")"
-  #         test "${SCORE%.*}" -ge 9
+      # Check if pass, the test command only takes integers so truncate decimals
+      - name: Check If Pass (90%)
+        run: |
+          SCORE="$(sed -n '$s/[^0-9]*\([0-9.]*\).*/\1/p' <<< "$(hatch run pylint esbmc_ai)")"
+          test "${SCORE%.*}" -ge 9
 
   test:
     name: PyTest
