Updated pylint workflow to fail only with scores under 9.0

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -69,8 +69,15 @@ jobs:
             ~/.local/share/hatch
           key: ${{ runner.os }}-hatch-${{ env.HATCH_DEP_HASH }}
 
+      # Don't fail just output, since we want the score to be above 9 not 10.0
+      # Don’t let the Perfect be the Enemy of the Good
       - name: Pylint on esbmc_ai
-        run: hatch run pylint esbmc_ai
+        run: hatch run pylint esbmc_ai || true
+      
+      - name: Check If Pass (90%)
+        run: |
+          SCORE="$(sed -n '$s/[^0-9]*\([0-9.]*\).*/\1/p' <<< "$(hatch run pylint esbmc_ai)")"
+          test "$SCORE" -gt 9
 
   test:
     name: PyTest
